server:
  port: 8080

spring:
  application:
    name: gateway

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka

zuul:
  ignored-services: "*"
  routes:
    auth:
      url: http://desktop-t6ktkse:8081/
      strip-prefix: false
      custom-sensitive-headers: true
